config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :matches, only: [:index, :new, :create]
  
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/match.rb
class Match < ApplicationRecord
  validates_presence_of :player_one
  validates_presence_of :player_two
  validates_presence_of :result
  validates :player_one, comparison: { other_than: :player_two, message: "and Player two should be different" }

  belongs_to :player_one, class_name: 'User'
  belongs_to :player_two, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  before_save :capitalize_names
  
  validates_presence_of :name
  validates_presence_of :surname
  validates_presence_of :rank
  validates_presence_of :games_played
  validates_presence_of :birthday
  validates :email   , presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :birthday, comparison: { less_than: 18.years.ago, message: "Must be older than 18"}
  
  def matches
    get_matchs_as_player_one(self).compact.concat(get_matchs_as_player_two(self))
  end

  private
  def capitalize_names
    self.name.capitalize!
    self.surname.capitalize!
  end

  def get_matchs_as_player_one(player)
    Match.where(player_one:player)
  end

  def get_matchs_as_player_two(player)
    Match.where(player_two:player)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all
  end

  def new
    @match = Match.new
    @users = User.all
  end

  def create
    player_one = User.find(match_params["player_one"])
    player_two = User.find(match_params["player_two"])
    result = match_params["result"]
    
    @match = Match.new(player_one:player_one, player_two:player_two, result:result)
    @users = User.all

    if @match.save
      update_players_info(@match)
      redirect_to users_path, notice: "Ranks updated and match successfully recorded."
    else
      render :new, status: :unprocessable_entity
    end

  end

  private

  def match_params
    params.require(:match).permit(:player_one, :player_two, :result)
  end

  def update_players_info(match)
    update_games_played(match.player_one)
    update_games_played(match.player_two)
    update_rank(match)
  end

  def update_games_played(player)
    User.where(:id => player.id).update_all(:games_played => player.matches.length)
  end

  def update_rank(match)
    one = match.player_one
    two = match.player_two
    result = match.result

    case result
      when 'Draw'
        if (-1..1).exclude?(one.rank - two.rank)
          one.rank > two.rank ? upgrade_rank(one) : upgrade_rank(two)
        end
      when 'Player 1 Won'
        if one.rank > two.rank
          jump_rank(one, two)
          downgrade_rank(two)
        end
      when 'Player 2 Won'
        if two.rank > one.rank
          jump_rank(two, one)
          downgrade_rank(one)
        end
      end
  end

  def downgrade_rank(player)
    User.where(:rank => player.rank + 1)[0].update(:rank => player.rank)
    player.update(:rank => player.rank + 1)
  end

  def upgrade_rank(player)
    User.where(:rank => player.rank - 1).update_all(:rank => player.rank)
    player.update(:rank => player.rank - 1)
  end

  def jump_rank(jumper, holder)
    jumper_rank = jumper.rank - ((jumper.rank - holder.rank)/2.0).round()
    until jumper_rank == jumper.rank do
      upgrade_rank(jumper)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.order('rank ASC')
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    @user.rank = User.all.length + 1
    @user.games_played = 0

    if @user.save
      redirect_to users_path, notice: "User was successfully created." 
    else
      render :new, status: :unprocessable_entity 
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_url(@user), notice: "User was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    update_ranks_on_delete_user(@user.rank + 1, User.all.size)
    @user.destroy
    redirect_to users_url, notice: "User was successfully destroyed."
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :surname, :email, :birthday, :games_played, :rank)
    end

    def update_ranks_on_delete_user(start, last)
      User.where(rank: (start..last)).to_a.each do |user|
        user.update(:rank => user.rank - 1)
      end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChessClubScoreboardRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matches/_match.html.erb
<div id="<%= dom_id match %>">
  <tr>
    <td><%= match.player_one.name %> <%=match.player_one.surname %></td>
    <td><%= match.player_two.name %> <%=match.player_two.surname %></td>
    <td><%= match.result %> </td>
  </tr>
</div>

app/views/matches/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Matches Records</h1>

<div id="matches">
  <table>
    <tr>
      <th><strong>Player 1</strong></th>
      <th><strong>Player 2</strong></th>
      <th><strong>Result</strong></th>
    </tr>
    <% if @matches.present? %>
      <% @matches.each do |match| %>
        <%= render partial: "match", :locals => {:match => match} %>
      <% end %>
    <% else%>
     <tr>
       <td colspan="4"><i><center>Empty</center></i></td>
     </tr>
    <% end %>
  </table>
</div>

<div>
  <%= link_to "New match", new_match_path %> 
</div>

<div>
  <%= link_to "Back to ranks", users_path %>
</div>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= form_with(model: @match) do |form| %>
  <% if @match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being recorded:</h2>

      <ul>
        <% @match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :player_one, style: "display: block" %>
    <%= form.collection_select :player_one, @users, :id, :name %>
  </div>

  <div>
    <%= form.label :player_two, style: "display: block" %>
    <%= form.collection_select :player_two, @users, :id, :name %>
  </div>
    <div>
    <%= form.label :result, style: "display: block" %>
    <%= form.select :result, ["Player 1 Won", "Player 2 Won", "Draw"] %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

<br>

<%= link_to "Back to ranks", users_path %>
<%= link_to "Back to matches", matches_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :surname, style: "display: block" %>
    <%= form.text_field :surname %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :birthday, style: "display: block" %>
    <%= form.date_field :birthday %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <h2><%= user.name %>'s Profile</h2>

  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Surname:</strong>
    <%= user.surname %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Birthday:</strong>
    <%= user.birthday %>
  </p>

  <p>
    <strong>Games played:</strong>
    <%= user.games_played %>
  </p>

  <p>
    <strong>Rank:</strong>
    <%= user.rank %>
  </p>

  <h3>Matches</h4>

  <div id="matches">
    <table>
      <tr>
        <th><strong>Player 1</strong></th>
        <th><strong>Player 2</strong></th>
        <th><strong>Result</strong></th>
      </tr>
      <% if user.matches.present? %>
        <% user.matches.each do |match| %>
          <%= render partial: "matches/match", :locals => {:match => match} %>
        <% end %>
      <% else%>
        <td colspan="3"><i><center>Empty</center></i></td>
      <% end %>
    </table>
  </div>
</div>

app/views/users/_user_index.html.erb
<tr id="<%= dom_id user %>">
    <td><%= user.id %></td>
    <td><%= user.name %> <%=user.surname %></td>
    <td><%= user.games_played %></td>
    <td>#<%= user.rank %></td>
    <td><%= link_to "Show", user %></td>
</tr>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users Ranks</h1>

<div id="users">
  <table>
    <tr>
      <th><strong>ID</strong></th>
      <th><strong>Name</strong></th>
      <th><strong>Games Played</strong></th>
      <th><strong>Rank</strong></th>
      <th><strong>Profile</strong></th>
    </tr>
  <% if @users.present? %>
    <% @users.each_with_index do |user,index| %>
      <%= render partial: "user_index", :locals => {:user => user, :index => index} %>
    <% end %>
  <% else%>
    <tr>
      <td colspan="5"><i><center>Empty</center></i></td>
    </tr>
  <% end %>
  </table>
</div>

<%= link_to "New user", new_user_path %>
<%= link_to "New match", new_match_path %>
<%= link_to "Show matches", matches_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to ranks", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to ranks", users_path %>

  <%= button_to "Delete this user", @user, method: :delete %>
</div>